ARG VARIANT=3-bullseye
FROM mcr.microsoft.com/vscode/devcontainers/python:0-${VARIANT}

# Customize the image as root

# Optionally customize the image as vscode
# USER 1000

# Make sure you switch back to root after
# USER 0

# copy hooks
# COPY hooks.d/post-start /usr/local/lib/devcontainer/hooks.d/post-start/

# Do not set an entrypoint
USER vscode